import {readFile,writeFile,mkdir} from 'node:fs/promises';
const papers=JSON.parse(await readFile('papers.json','utf8'));
import {page} from './layout.mjs';
const [research,about,service]=await Promise.all(['research.html','about.html','service.html'].map(file=>readFile(file,'utf8')));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const authors=p=>esc(p.authors).replaceAll('Tiancheng Hu','<strong>Tiancheng Hu</strong>');
function row(p){return `<li class="paper" data-search="${esc([p.title,p.authors,p.venue,p.year].join(' ').toLowerCase())}"><a class="paper-title" href="${esc(p.url)}">${esc(p.title)}</a><div class="authors">${authors(p)}</div><div class="venue"><em>${esc(p.venue)}</em>, ${p.year}. <a href="${esc(p.url)}">[paper]</a> <a href="/publication/${p.slug}/">[cite]</a></div></li>`}
await writeFile('../index.html',page('Tiancheng Hu',`${about}${research}${service}`));
await mkdir('../publication',{recursive:true});
await writeFile('../publication/index.html',page('Publications | Tiancheng Hu',`<a class="back" href="/">← Tiancheng Hu</a><h1>Publication archive</h1><p>For my full, current publication list, visit <a href="https://scholar.google.com/citations?user=Na1GOYgAAAAJ&amp;hl=en">Google Scholar</a>.</p><label for="paper-search">Search by title, author, venue, or year</label><input id="paper-search" class="search" type="search" autocomplete="off"><p id="result-count" class="result-count" role="status">${papers.length} publications</p><ul class="paper-list">${papers.map(row).join('')}</ul><p id="empty" hidden>No matching publications.</p>`));
for(const p of papers){const bib=p.bib||`@article{hu${p.year}${p.slug.replace(/[^a-z0-9]/g,'')},\n  title = {${p.title}},\n  author = {${p.authors.split(', ').join(' and ')}},\n  year = {${p.year}},\n  url = {${p.url}}\n}`;const dir=`../publication/${p.slug}`;await mkdir(dir,{recursive:true});await writeFile(`${dir}/cite.bib`,bib);await writeFile(`${dir}/index.html`,page(`${p.title} | Tiancheng Hu`,`<a class="back" href="/">← Tiancheng Hu</a><article class="paper-detail"><h1>${esc(p.title)}</h1><p>${authors(p)}</p><p><em>${esc(p.venue)}</em>, ${p.year}.</p><p><a href="${esc(p.url)}">Read paper</a> · <a href="cite.bib" download>Download BibTeX</a></p><h2>Citation</h2><pre id="citation">${esc(bib)}</pre><button id="copy-citation" type="button">Copy BibTeX</button><span id="copy-status" role="status"></span></article>`));}
await writeFile('../404.html',page('Page not found | Tiancheng Hu','<h1>Page not found</h1><p><a href="/">Return to Tiancheng Hu’s homepage</a> or <a href="/publication/">browse publications</a>.</p>'));
console.log(`Rendered simple academic homepage, search, and ${papers.length} publication pages.`);
